\\ ---------------------------------------------------------------------------
\\ setup108.gp
\\
\\ Elliptic Gamma invariants for the six narrow ray classes of K = Q(beta),
\\ beta^3 = 2 (discriminant -108), conductor ff = (3), smoothing ideal
\\ aa = p5 (the degree-one prime above 5), following BCG (arXiv:2311.04110)
\\ section 5.3.  Companion of setup23c.gp (disc -23, section 5.4).
\\
\\ Cl+_ff = Z/6, generated by the class of (beta) (norm 2, (beta)^3 = (2)).
\\ Class representatives: IDEALB = (beta)^k, k = 0..5.  The generator of
\\ O^{+,x}_ff is (beta-1)^3; the exponent 3 is detected at run time from
\\ the fundamental unit (compare the hard-coded 24 of the -23 case).
\\ The invariants are matched against the sextic of BCG 5.3:
\\   P6 = x^6-(3b^2-9b+6)x^5+(23b^2-17b-16)x^4+(48b^2-43b-23)x^3
\\           +(23b^2-17b-16)x^2-(3b^2-9b+6)x+1
\\ (b = complex root of y^3-2 with Im(b) < 0).  Observed matching:
\\   class 0 -> r1,  class 1 -> r2,  class 2 -> r3,
\\   class 3 -> r6,  class 4 -> r5,  class 5 -> r4  (all six roots, distinct),
\\ satisfying the tau-law u(k+3) = 1/u(k) of BCG Remark 2 (palindromy) and
\\ realizing the reciprocity orbit under sigma_{(beta)}.  This REQUIRES the
\\ marking normalization FACTOR = -rhosign (see rhosign below); with the
\\ former hard-coded FACTOR = 1, classes k and k+3 folded onto the same
\\ number, an inversion artefact, not a property of the conjecture.
\\
\\ Requires: Baby_step_GammaFelder33.gp in the same directory.
\\ Usage:    gp -q setup108.gp        (runs the six classes)
\\           Edit TARGETDIGITS below; runclass(k) runs a single class k=0..5.
\\
\\ Cost guide (one core): every class has wedge width ss = 9, i.e. 18 calls;
\\ about 0.15 s per class at 25 digits, under a second at 40 digits, and an
\\ estimated few minutes for all six classes at 1000 digits (per-call costs
\\ transferred from the measured -23 wedges of the same geometry).
\\ ---------------------------------------------------------------------------

\\ GP pitfall: a parisizemax reallocation occurring INSIDE a read() silently
\\ aborts the remainder of the file being read.  This script is meant to be
\\ run directly (gp -q setup108.gp); to read() it from a session instead,
\\ set parisizemax >= 2*10^9 beforehand (the guard below then does nothing).
if(default(parisizemax) < 2*10^9, default(parisizemax, 2*10^9));

\\ ----------------------------- parameters ----------------------------------

TARGETDIGITS = 25;                   \\ aimed decimals
PREC   = TARGETDIGITS + 20;          \\ working precision (decimal digits)
BDTERM = TARGETDIGITS + 10;          \\ stop threshold 10^(-BDTERM) in the Lambert series
BBD    = 8*BDTERM;                   \\ max terms; MUST grow with BDTERM
default(realprecision, PREC);

read("Baby_step_GammaFelder33.gp");

\\ ----------------------------- the field -----------------------------------

K108 = bnfinit(y^3 - 2);
p5   = idealprimedec(K108, 5)[1];            \\ the degree-one prime, norm 5
bgen = idealhnf(K108, Mod(y, K108.pol));     \\ (beta), generator of Cl+_ff

\\ ------------------ utilities, verbatim from exK7oct.gp --------------------

outil3gcd(x,u0,v0)={
local(D,x1,y1,xx,yy, attempt);
[xx, yy,D]=gcdext(u0,v0);
q=floor(x/D);
x1=-q*xx;
y1=-q*yy;
attempt=x+(u0*x1+v0*y1);
if(attempt<0, print("attention"));
if(attempt>D-1, print("attention"));
return([x1,y1])
}

COSET(B1, b)={
local(d1,d2,d3, LIST);
LIST=listcreate();
for(d1=0, B1-1,
  [d2, d3]=outil3gcd(d1*b[1],b[2],b[3]);
  listput(LIST, [d1,d2,d3]));
return(LIST)
}

Hermitesmallsur2(M)={
local(test, try,q,r, MM, INVOL, H, V, U,UU,  HH, transv1, transv2,transv3);
MM=matdet(M)*M^(-1);
test=mathnf(MM, 1);
H=test[1];
V=test[2];
if(matdet(V)==-1, V=-V);
HH=H^(-1)*matdet(M);
UU=V^(-1);
u=HH[1, 2]; v=HH[2, 2];
s=HH[2, 3]; t=HH[3, 3];
if(abs(u)>abs(v)/2 , q=round(u/v); transv1=[1,-q,0;0,1,0; 0,0,1]; UU=transv1*UU;
HH=transv1*HH);
r=HH[1, 3];
if(abs(s)>abs(t)/2 , q=round(s/t); transv2=[1,0,0;0,1,-q; 0,0,1]; UU=transv2*UU;
HH=transv2*HH);
if(abs(r)>abs(t)/2 , q=round(r/t); transv3=[1,0,-q;0,1,0; 0,0,1]; UU=transv3*UU;
HH=transv3*HH);
if(HH[1, 1]<0, UU=[-1,0,0;0,-1,0; 0,0,1]*UU; HH=[-1,0,0;0,-1,0; 0,0,-1]*HH);
if(HH[2, 2]<0, UU=[1,0,0; 0,-1,0; 0,0,-1]*UU; HH=[1,0,0;0,-1,0; 0,0,-1]*HH);
return([UU, HH])
}

gpouraabb(aa,bb)={
local(UU,HH,  MM);
MM=[aa[1], bb[1], prime(7); aa[2], bb[2], prime(3); aa[3], bb[3], prime(5)];
[UU, HH]=Hermitesmallsur2(MM);
if(HH[1,1]==1, , print("attention", HH[1,1]));
return([UU, HH[2, 2]])
}

findera(gam,u)={
local(M);
M=matrix(2, 3);
M[1, ]=gam;
M[2, ]=gam*u;
return(matkerint(M,)~)
}

\\ -------------------- class data (splits EXcalcul in two) ------------------
\\ epspow_detect: smallest m >= 1 with eps^m = 1 mod RAM (eps normalized in
\\ (0,1)); this is Pierre's idealadd test from the original EXcalcul, made
\\ automatic.  Gives 3 here ((beta-1)^3) and 24 for the -23 field.

epspow_detect(FF, RAM)={
local(rooot,eps,eps1,RAMid,m0,II);
rooot = polroots(FF.pol)[1];
eps1 = lift(FF.fu)[1];
eps  = real(subst(lift(FF.fu), y, rooot)[1]);
if(eps<0, eps=-eps; eps1=-eps1);
if(eps>1, eps=1/eps; eps1=lift(Mod(1/eps1,FF.pol)));
RAMid = idealhnf(FF, RAM);
m0 = 0;
for(m=1, 200,
  II = idealadd(FF, Mod(eps1, FF.pol)^m - 1, RAMid);
  if(idealnorm(FF, II) == idealnorm(FF, RAMid), m0 = m; break));
if(m0==0, error("no unit power = 1 mod RAM up to 200"));
return(m0)
}

\\ getbasis: everything depending only on the class representative IDEALB.
\\ Returns [om1,om2,om3, MAT2, MM, N, Qq, rooot, xx0] where xx0 is the
\\ eigencolumn of MAT2 with NON-REAL eigenvalue of NEGATIVE imaginary part
\\ (same convention as setup23c; the other column computes the conjugate
\\ sextic).  EPSPOW is the exponent from epspow_detect.

getbasis(FF, SMOOTH, RAM, IDEALB, EPSPOW)={
local(rooot,N,Qq,LL,AABB,AALL,HN0,HN2,MATMAT,uu,vv,dd,eps,eps1,Eps,
      L1,L2,L3,MAT2,MM,ommm1,ommm2,ommm3,omm1,omm2,omm3,om1,om2,om3,
      mu1,mu2,mu3,Lk1,Lk2,Lk3,LAM,VEC,jc);
rooot = polroots(FF.pol)[1];              \\ the real root: real coordinates
N     = idealnorm(FF, SMOOTH);
Qq    = idealdown(FF, RAM);
LL    = idealdiv(FF, RAM, IDEALB,);
AABB  = idealmul(FF, SMOOTH, IDEALB);
AALL  = idealdiv(FF, RAM, AABB,);
HN0 = idealhnf(FF, AALL);
[ommm1,ommm2,ommm3] = subst(FF.zk*HN0, y, rooot);
[omm1,omm2,omm3]    = [ommm1/Qq, ommm2, ommm3];
HN2 = idealhnf(FF, LL);
[mu1,mu2,mu3] = subst(FF.zk*HN2, y, rooot);
Lk1 = lindep([omm1,omm2,omm3, mu1]);
Lk2 = lindep([omm1,omm2,omm3, mu2]);
Lk3 = lindep([omm1,omm2,omm3, mu3]);
MATMAT = -[Lk1[1],Lk1[2],Lk1[3]; Lk2[1],Lk2[2],Lk2[3]; Lk3[1],Lk3[2],Lk3[3]];
[uu,vv,dd] = matsnf(MATMAT, 1);
if(dd[1,1] != N*Qq, print("WARNING SNF diag = ", [dd[1,1],dd[2,2],dd[3,3]]));
[om3,om2,om1] = [omm1,omm2,omm3]*mattranspose(vv^(-1))*[N*Qq,0,0; 0,1,0; 0,0,1];
eps1 = lift(FF.fu)[1];
eps  = real(subst(lift(FF.fu), y, rooot)[1]);
if(eps<0, eps=-eps; eps1=-eps1);
if(eps>1, eps=1/eps; eps1=lift(Mod(1/eps1,FF.pol)));
Eps = eps^EPSPOW;                          \\ generator of O^{+,x}_ff
L1 = lindep([om1,om2,om3, Eps*om1]);
L2 = lindep([om1,om2,om3, Eps*om2]);
L3 = lindep([om1,om2,om3, Eps*om3]);
MAT2 = [L1[1],L1[2],L1[3]; L2[1],L2[2],L2[3]; L3[1],L3[2],L3[3]];
if(matdet(MAT2)<0, MAT2 = -MAT2);
if(matdet(MAT2)!=1, print("WARNING det MAT2 = ", matdet(MAT2)));
MM = lindep([om1,om2,om3, -1]);
MM = sign(MM[4])*MM;                       \\ coordinates of 1: MM[1..3]/MM[4]
[LAM,VEC] = mateigen(MAT2, 1);
jc = 0; for(j=1, 3, if(imag(LAM[j]) < 0, jc = j));
if(jc==0, error("no eigenvalue with negative imaginary part"));
return([om1,om2,om3, MAT2, MM, N, Qq, rooot, VEC[,jc]])
}

\\ getwedge: the (jjj,kkk,lll)-dependent part.  gamma = [N*Qq*jjj, N*Qq*kkk,
\\ MM[3]+Qq*lll] MUST be primitive over Z, otherwise the congruence class of
\\ the smoothing is destroyed (checked, fatal).  Returns [TAU,SIGMA,ZL,N,ss,gam].

getwedge(BAS, jjj,kkk,lll, FACTOR)={
local(om1,om2,om3,MAT2,MM,N,Qq,gam,aa,bb,UU,ss,bbb,newb,uu,vv,tt,
      kk,ll,dd,beta,alpha,GAMMA,xx,TAU,SIGMA,LISTEF,ZL,d1,d2,d3,zz,h,PERT);
om1=BAS[1]; om2=BAS[2]; om3=BAS[3]; MAT2=BAS[4]; MM=BAS[5]; N=BAS[6]; Qq=BAS[7];
gam = [N*Qq*jjj, N*Qq*kkk, MM[3] + Qq*lll];
if(content(gam) != 1, error("gamma not primitive: ", gam));
aa = findera(gam, MAT2);
bb = (MAT2*aa~)~;
[UU, ss] = gpouraabb([aa[1,1],aa[1,2],aa[1,3]], [bb[1,1],bb[1,2],bb[1,3]]);
bbb  = [bb[1,1],bb[1,2],bb[1,3]];
newb = UU*(bbb~);
[uu,vv,tt] = newb~;
LISTEF = COSET(ss, newb~);
[kk,ll,dd] = gcdext(vv,tt);
if(dd != ss, error("gcd(v,t) = ", dd, " differs from ss = ", ss));
beta  = [0, kk, ll];
alpha = [ss,0,0] - uu*beta;
GAMMA = [0, -tt/ss, vv/ss];
xx = (UU*BAS[9])~;
TAU   = (alpha*xx~)/(GAMMA*xx~);
SIGMA = (beta *xx~)/(GAMMA*xx~);
PERT = 1.*10^(5-PREC);
ZL = listcreate();
for(h=1, length(LISTEF),
  [d1,d2,d3] = LISTEF[h];
  zz = (([d1,d2,d3] - GAMMA*FACTOR/Qq)*xx~)/(GAMMA*xx~);
  listput(ZL, zz + I*PERT));
return([TAU, SIGMA, ZL, N, ss, gam])
}

\\ naive decay rate of the wedge (cost model of the certified Sage chain)
rho_of(z, T, S) = Pi*abs(imag(T)) + Pi*abs(imag(S)) - Pi*abs(imag(2*z-T-S));

\\ ----------------------- invariant of one wedge ----------------------------

\\ rhosign: sign relating the Hermite pipeline's effective gamma to the
\\ admissible vector gam.  The z-shift of getwedge evaluates the marking
\\ -FACTOR*gamma_code/q, so FACTOR = -rhosign evaluates at w = +h(x), the
\\ normalization of BCG Def. admissibility (lambda/q = 1 mod L); with any
\\ other choice the computed number is the INVERSE unit (tau-twist).

rhosign(BAS, jjj,kkk,lll)={
local(MAT2,MM,N,Qq,gam,aa,bb,UU,ss,newb,uu,vv,tt,cc,pr);
MAT2=BAS[4]; MM=BAS[5]; N=BAS[6]; Qq=BAS[7];
gam = [N*Qq*jjj, N*Qq*kkk, MM[3] + Qq*lll];
aa = findera(gam, MAT2);
bb = (MAT2*aa~)~;
[UU, ss] = gpouraabb([aa[1,1],aa[1,2],aa[1,3]], [bb[1,1],bb[1,2],bb[1,3]]);
newb = UU*([bb[1,1],bb[1,2],bb[1,3]]~);
[uu,vv,tt] = newb~;
cc = [0, -tt/ss, vv/ss]*UU;
pr = 0; for(j=1,3, if(gam[j]!=0 && pr==0, pr = cc[j]/gam[j]));
return(sign(pr));
}

classinvariant(BAS, jjj,kkk,lll)={
local(W,TAU,SIG,ZL,NA,ss,gam,rhomin,rr,PROD,PRODBIS,z1,z2,i,TOT,rho);
rho = rhosign(BAS, jjj,kkk,lll);
print("  rho=", rho, "  FACTOR=", -rho, "  (evaluation at w=+h)");
W = getwedge(BAS, jjj,kkk,lll, -rho);
TAU=W[1]; SIG=W[2]; ZL=W[3]; NA=W[4]; ss=W[5]; gam=W[6];
rhomin = 10^9;
for(i=1, length(ZL), rr = rho_of(ZL[i],TAU,SIG); if(rr<rhomin, rhomin=rr));
print("  triple=[",jjj,",",kkk,",",lll,"]  ss=",ss,"  gam=",gam,
      "  gam3 mod 3 = ", lift(Mod(gam[3],3)));
print("  Im tau=", imag(TAU), "  Im sigma=", imag(SIG), "  rho_min=", rhomin);
gettime();
PROD=1.; PRODBIS=1.;
for(i=1, length(ZL),
  z1 = ZL[i];    z1 = z1 - round(real(z1));
  z2 = NA*ZL[i]; z2 = z2 - round(real(z2));
  PROD    = PROD    * lessnaifGamma(z1, TAU,    SIG,    BBD, BDTERM);
  PRODBIS = PRODBIS * lessnaifGamma(z2, NA*TAU, NA*SIG, BBD, BDTERM);
  if(i%300==0, print("  progress ", i, "/", ss, "  block ms=", gettime())));
TOT = PROD^NA/PRODBIS;
print("  time ms = ", gettime());
return([TOT, ss, gam, rhomin])
}

\\ ----------------------- sextic of BCG 5.3 and matching --------------------

sextic53(b)=
{
x^6 - (3*b^2-9*b+6)*x^5 + (23*b^2-17*b-16)*x^4 + (48*b^2-43*b-23)*x^3
    + (23*b^2-17*b-16)*x^2 - (3*b^2-9*b+6)*x + 1;
}

matchreport(TOT)={
local(rts,b,Q,RO,c,k,d,best,bestk,CAND,LAB,res);
rts = polroots(y^3-2);
b = 0; for(k=1,3, if(imag(rts[k]) < -1e-10, b = rts[k]));
Q  = sextic53(b);
RO = polroots(Q);
print("  |P6(TOT)| = ", abs(subst(Q, x, TOT)));
CAND = [TOT, 1/TOT]; LAB = ["  u   ", "  1/u "]; res = [0,0];
for(c=1, 2,
  best = 10^9; bestk = 0;
  for(k=1, 6, d = abs(CAND[c]-RO[k]); if(d<best, best=d; bestk=k));
  print(LAB[c], "= root ", bestk, "  dist = ", best);
  res[c] = if(best < 1e-6, bestk, 0));
return(res)
}

\\ ------------------------------- driver ------------------------------------

CLASSTRIPLE = [[-1,0,-1], [1,0,0], [1,1,0], [1,0,0], [-1,0,-1], [-1,-1,-1]];
RESULTS     = vector(6, i, 0);
EPSPOW108   = 0;

runclass(kcl)={
local(BAS,R,T,IB);
if(EPSPOW108==0, EPSPOW108 = epspow_detect(K108, 3);
   print("unit exponent detected: eps_ff = eps^", EPSPOW108));
print("=========== class ", kcl, "   IDEALB = (beta)^", kcl, " ===========");
IB = if(kcl==0, idealhnf(K108,1), idealpow(K108, bgen, kcl));
BAS = getbasis(K108, p5, 3, IB, EPSPOW108);
T = CLASSTRIPLE[kcl+1];
R = classinvariant(BAS, T[1], T[2], T[3]);
print("  TOT = ", R[1]);
matchreport(R[1]);
RESULTS[kcl+1] = R[1];
write(Str("invariant_disc-108_class", kcl, ".txt"), R[1]);
return(R[1])
}

runall()={
print("K = Q(beta), beta^3 = 2, disc -108, ff = (3), aa = p5, ",
      TARGETDIGITS, " digits target");
for(kcl=0, 5, runclass(kcl));
print("=========== summary ===========");
for(kcl=0, 5, print("class ", kcl, " : ", RESULTS[kcl+1]));
}

runall()
